function runAnimations() {
  document.querySelector("#id-4864").addEventListener("click", func_4864_4854);

  function func_4864_4854(e) {
    e.stopPropagation();

    document.querySelector("#id-15").classList.add("animationClass-15");
    document.querySelector("#id-111").classList.add("animationClass-111");
    document.querySelector("#id-252").classList.add("animationClass-252");
    document.querySelector("#id-253").classList.add("animationClass-253");
    document.querySelector("#id-24").classList.add("animationClass-24");
    document.querySelector("#id-23").classList.add("animationClass-23");
    document.querySelector("#id-211").classList.add("animationClass-211");
    document
      .querySelector(".ira-1-308722-0")
      .classList.add("animationClass-115-115-0");
    document.querySelector("#id-115").classList.add("animationClass-115");
    document.querySelector("#id-219").classList.add("animationClass-219");
    document.querySelector("#id-220").classList.add("animationClass-220");
    document.querySelector("#id-221").classList.add("animationClass-221");
    document
      .querySelector(".car-1-10816-0")
      .classList.add("animationClass-222-222-0");
    document.querySelector("#id-222").classList.add("animationClass-222");
    document.querySelector("#id-215").classList.add("animationClass-215");
    document.querySelector("#id-216").classList.add("animationClass-216");
    document.querySelector("#id-217").classList.add("animationClass-217");
    document
      .querySelector(".c-401k-1-563539-0")
      .classList.add("animationClass-218-218-0");
    document.querySelector("#id-218").classList.add("animationClass-218");
    document.querySelector("#id-4864").classList.add("animationClass-4864");
    document
      .querySelector(".investment-acco-1-591360-0")
      .classList.add("animationClass-4850-4850-0");
    document.querySelector("#id-4850").classList.add("animationClass-4850");
    document.querySelector("#id-57104").classList.add("animationClass-57104");
    document.querySelector("#id-57105").classList.add("animationClass-57105");
    document.querySelector("#id-105217").classList.add("nullAnimation-105217");
    document.querySelector("#id-105218").classList.add("nullAnimation-105218");
    document.querySelector("#id-105219").classList.add("nullAnimation-105219");
    document.querySelector("#id-105235").classList.add("nullAnimation-105235");
    document.querySelector("#id-105236").classList.add("nullAnimation-105236");
    document.querySelector("#id-105225").classList.add("nullAnimation-105225");
    document.querySelector("#id-105226").classList.add("nullAnimation-105226");
    document.querySelector("#id-105227").classList.add("nullAnimation-105227");
    document.querySelector("#id-105228").classList.add("nullAnimation-105228");
    document.querySelector("#id-105229").classList.add("nullAnimation-105229");
    document.querySelector("#id-105220").classList.add("nullAnimation-105220");
    document.querySelector("#id-105221").classList.add("nullAnimation-105221");
    document.querySelector("#id-105222").classList.add("nullAnimation-105222");
    document.querySelector("#id-105223").classList.add("nullAnimation-105223");
    document.querySelector("#id-105224").classList.add("nullAnimation-105224");
    document.querySelector("#id-105230").classList.add("nullAnimation-105230");
    document.querySelector("#id-105231").classList.add("nullAnimation-105231");
    document.querySelector("#id-105233").classList.add("nullAnimation-105233");
    document.querySelector("#id-105232").classList.add("nullAnimation-105232");
    document.querySelector("#id-105234").classList.add("nullAnimation-105234");
    document.querySelector("#id-6290").classList.add("nullAnimation-6290");
    document.querySelector("#id-6291").classList.add("nullAnimation-6291");
    document.querySelector("#id-6292").classList.add("nullAnimation-6292");
    document.querySelector("#id-10110").classList.add("nullAnimation-10110");
    document.querySelector("#id-3712").classList.add("nullAnimation-3712");
    document.querySelector("#id-223").classList.add("nullAnimation-223");
    document.querySelector("#id-94231").classList.add("nullAnimation-94231");
    document.querySelector("#id-3027").classList.add("nullAnimation-3027");
    document.querySelector("#id-94169").classList.add("nullAnimation-94169");
    document.querySelector("#id-2511").classList.add("nullAnimation-2511");
    document.querySelector("#id-258").classList.add("nullAnimation-258");
    document.querySelector("#id-259").classList.add("nullAnimation-259");
    document.querySelector("#id-2510").classList.add("nullAnimation-2510");
    document.querySelector("#id-10111").classList.add("nullAnimation-10111");
    document.querySelector("#id-257").classList.add("nullAnimation-257");
    document.querySelector("#id-254").classList.add("nullAnimation-254");
    document.querySelector("#id-255").classList.add("nullAnimation-255");
    document.querySelector("#id-256").classList.add("nullAnimation-256");
    document.querySelector("#id-94230").classList.add("nullAnimation-94230");
    document.querySelector("#id-2516").classList.add("nullAnimation-2516");
    document.querySelector("#id-2514").classList.add("nullAnimation-2514");
    document.querySelector("#id-2512").classList.add("nullAnimation-2512");
    document.querySelector("#id-2513").classList.add("nullAnimation-2513");
    document.querySelector("#id-102").classList.add("animationClass-null102");
    document.querySelector("#id-1010").classList.add("animationClass-null1010");
    document.querySelector("#id-4561").classList.add("animationClass-null4561");
    document.querySelector("#id-1029").classList.add("animationClass-null1029");
    document.querySelector("#id-1030").classList.add("animationClass-null1030");
    document.querySelector("#id-1031").classList.add("animationClass-null1031");
    document.querySelector("#id-1032").classList.add("animationClass-null1032");
    document
      .querySelector("#id-1032 > div:first-child")
      .classList.add("bgClass-1032");
    document.querySelector("#id-1023").classList.add("animationClass-null1023");
    document.querySelector("#id-1018").classList.add("animationClass-null1018");
    document.querySelector("#id-1014").classList.add("animationClass-null1014");
    document.querySelector("#id-1034").classList.add("animationClass-null1034");
    document
      .querySelector("#id-1034 > div:first-child")
      .classList.add("bgClass-1034");
    document.querySelector("#id-1024").classList.add("animationClass-null1024");
    document.querySelector("#id-1019").classList.add("animationClass-null1019");
    document.querySelector("#id-1015").classList.add("animationClass-null1015");
    document.querySelector("#id-1036").classList.add("animationClass-null1036");
    document
      .querySelector("#id-1036 > div:first-child")
      .classList.add("bgClass-1036");
    document.querySelector("#id-1022").classList.add("animationClass-null1022");
    document.querySelector("#id-1017").classList.add("animationClass-null1017");
    document.querySelector("#id-1012").classList.add("animationClass-null1012");
    document.querySelector("#id-1035").classList.add("animationClass-null1035");
    document
      .querySelector("#id-1035 > div:first-child")
      .classList.add("bgClass-1035");
    document.querySelector("#id-1021").classList.add("animationClass-null1021");
    document.querySelector("#id-1016").classList.add("animationClass-null1016");
    document.querySelector("#id-1013").classList.add("animationClass-null1013");
    document.querySelector("#id-1033").classList.add("animationClass-null1033");
    document
      .querySelector("#id-1033 > div:first-child")
      .classList.add("bgClass-1033");
    document.querySelector("#id-3745").classList.add("animationClass-null3745");
    document.querySelector("#id-3746").classList.add("animationClass-null3746");
    document.querySelector("#id-3759").classList.add("animationClass-null3759");
    document
      .querySelector("#id-3759 > div:first-child")
      .classList.add("bgClass-3759");
    document.querySelector("#id-3751").classList.add("animationClass-null3751");
    document.querySelector("#id-3752").classList.add("animationClass-null3752");
    document.querySelector("#id-3753").classList.add("animationClass-null3753");
    document.querySelector("#id-3754").classList.add("animationClass-null3754");
    document.querySelector("#id-3747").classList.add("animationClass-null3747");
    document.querySelector("#id-3748").classList.add("animationClass-null3748");
    document.querySelector("#id-3749").classList.add("animationClass-null3749");
    document.querySelector("#id-3750").classList.add("animationClass-null3750");
    document
      .querySelector("#id-3750 > div:first-child")
      .classList.add("bgClass-3750");
    document.querySelector("#id-3755").classList.add("animationClass-null3755");
    document.querySelector("#id-3757").classList.add("animationClass-null3757");
    document.querySelector("#id-3756").classList.add("animationClass-null3756");
    document
      .querySelector("#id-3756 > div:first-child")
      .classList.add("bgClass-3756");
    document.querySelector("#id-3758").classList.add("animationClass-null3758");
    document
      .querySelector("#id-3758 > div:first-child")
      .classList.add("bgClass-3758");
    document.querySelector("#id-6252").classList.add("nullAnimation-6252");
    document.querySelector("#id-6253").classList.add("nullAnimation-6253");
    document.querySelector("#id-6254").classList.add("nullAnimation-6254");
    document.querySelector("#id-6255").classList.add("nullAnimation-6255");
    document.querySelector("#id-6258").classList.add("nullAnimation-6258");
    document.querySelector("#id-6256").classList.add("nullAnimation-6256");
    document.querySelector("#id-6257").classList.add("nullAnimation-6257");
    document.querySelector("#id-10110").classList.add("animationClass-10110");
    document
      .querySelector("#id-4864")
      .removeEventListener("click", func_4864_4854);

    setTimeout(() => {
      document
        .querySelector("#id-1029")
        .addEventListener("click", func_1029_6251);
    }, 100);
  }

  function func_1029_6251(e) {
    e.stopPropagation();

    document.querySelector("#id-15").classList.add("animationClass-4854");
    document.querySelector("#id-111").classList.add("nullAnimation-111");
    document.querySelector("#id-252").classList.add("nullAnimation-252");
    document.querySelector("#id-253").classList.add("nullAnimation-253");
    document.querySelector("#id-24").classList.add("nullAnimation-24");
    document.querySelector("#id-219").classList.add("nullAnimation-219");
    document.querySelector("#id-215").classList.add("nullAnimation-215");
    document.querySelector("#id-4864").classList.add("nullAnimation-4864");
    document
      .querySelector("#id-105217")
      .classList.add("animationClass-null105217");
    document
      .querySelector("#id-105218")
      .classList.add("animationClass-null105218");
    document
      .querySelector("#id-105219")
      .classList.add("animationClass-null105219");
    document
      .querySelector("#id-105235")
      .classList.add("animationClass-null105235");
    document
      .querySelector("#id-105236")
      .classList.add("animationClass-null105236");
    document
      .querySelector("#id-105236 > div:first-child")
      .classList.add("bgClass-105236");
    document
      .querySelector("#id-105225")
      .classList.add("animationClass-null105225");
    document
      .querySelector("#id-105226")
      .classList.add("animationClass-null105226");
    document
      .querySelector("#id-105227")
      .classList.add("animationClass-null105227");
    document
      .querySelector("#id-105228")
      .classList.add("animationClass-null105228");
    document
      .querySelector("#id-105229")
      .classList.add("animationClass-null105229");
    document
      .querySelector("#id-105220")
      .classList.add("animationClass-null105220");
    document
      .querySelector("#id-105221")
      .classList.add("animationClass-null105221");
    document
      .querySelector("#id-105222")
      .classList.add("animationClass-null105222");
    document
      .querySelector("#id-105223")
      .classList.add("animationClass-null105223");
    document
      .querySelector("#id-105224")
      .classList.add("animationClass-null105224");
    document
      .querySelector("#id-105224 > div:first-child")
      .classList.add("bgClass-105224");
    document
      .querySelector("#id-105230")
      .classList.add("animationClass-null105230");
    document
      .querySelector("#id-105231")
      .classList.add("animationClass-null105231");
    document
      .querySelector("#id-105233")
      .classList.add("animationClass-null105233");
    document
      .querySelector("#id-105232")
      .classList.add("animationClass-null105232");
    document
      .querySelector("#id-105232 > div:first-child")
      .classList.add("bgClass-105232");
    document
      .querySelector("#id-105234")
      .classList.add("animationClass-null105234");
    document
      .querySelector("#id-105234 > div:first-child")
      .classList.add("bgClass-105234");
    document.querySelector("#id-6290").classList.add("animationClass-null6290");
    document.querySelector("#id-6291").classList.add("animationClass-null6291");
    document.querySelector("#id-6292").classList.add("animationClass-null6292");
    document
      .querySelector("#id-6292 > div:first-child")
      .classList.add("bgClass-6292");
    document.querySelector("#id-102").classList.add("animationClass-102");
    document.querySelector("#id-6252").classList.add("animationClass-null6252");
    document.querySelector("#id-6253").classList.add("animationClass-null6253");
    document.querySelector("#id-6254").classList.add("animationClass-null6254");
    document.querySelector("#id-6255").classList.add("animationClass-null6255");
    document.querySelector("#id-6258").classList.add("animationClass-null6258");
    document.querySelector("#id-6256").classList.add("animationClass-null6256");
    document.querySelector("#id-6257").classList.add("animationClass-null6257");
    document.querySelector("#id-10110").classList.add("nullAnimation-10110");
    document
      .querySelector("#id-1029")
      .removeEventListener("click", func_1029_6251);

    setTimeout(() => {
      document
        .querySelector("#id-105220")
        .addEventListener("click", func_105220_15);
    }, 100);
  }

  function func_105220_15(e) {
    e.stopPropagation();

    document.querySelector("#id-15").classList.add("animationClass-6251");
    document.querySelector("#id-111").classList.add("animationClass-null111");
    document.querySelector("#id-252").classList.add("animationClass-null252");
    document.querySelector("#id-253").classList.add("animationClass-null253");
    document.querySelector("#id-24").classList.add("animationClass-null24");
    document.querySelector("#id-219").classList.add("animationClass-null219");
    document.querySelector("#id-215").classList.add("animationClass-null215");
    document.querySelector("#id-4864").classList.add("animationClass-null4864");
    document.querySelector("#id-105217").classList.add("animationClass-105217");
    document.querySelector("#id-6290").classList.add("animationClass-6290");
    document
      .querySelector("#id-10110")
      .classList.add("animationClass-null10110");
    document.querySelector("#id-3712").classList.add("animationClass-null3712");
    document.querySelector("#id-223").classList.add("animationClass-null223");
    document
      .querySelector("#id-94231")
      .classList.add("animationClass-null94231");
    document.querySelector("#id-3027").classList.add("animationClass-null3027");
    document
      .querySelector("#id-3027 > div:first-child")
      .classList.add("bgClass-3027");
    document
      .querySelector("#id-94169")
      .classList.add("animationClass-null94169");
    document.querySelector("#id-2511").classList.add("animationClass-null2511");
    document.querySelector("#id-258").classList.add("animationClass-null258");
    document.querySelector("#id-259").classList.add("animationClass-null259");
    document.querySelector("#id-2510").classList.add("animationClass-null2510");
    document
      .querySelector("#id-10111")
      .classList.add("animationClass-null10111");
    document.querySelector("#id-257").classList.add("animationClass-null257");
    document.querySelector("#id-254").classList.add("animationClass-null254");
    document.querySelector("#id-255").classList.add("animationClass-null255");
    document.querySelector("#id-256").classList.add("animationClass-null256");
    document
      .querySelector("#id-256 > div:first-child")
      .classList.add("bgClass-256");
    document
      .querySelector("#id-94230")
      .classList.add("animationClass-null94230");
    document.querySelector("#id-2516").classList.add("animationClass-null2516");
    document.querySelector("#id-2514").classList.add("animationClass-null2514");
    document.querySelector("#id-2512").classList.add("animationClass-null2512");
    document
      .querySelector("#id-2512 > div:first-child")
      .classList.add("bgClass-2512");
    document.querySelector("#id-2513").classList.add("animationClass-null2513");
    document
      .querySelector("#id-2513 > div:first-child")
      .classList.add("bgClass-2513");
    document.querySelector("#id-102").classList.add("nullAnimation-102");
    document.querySelector("#id-6252").classList.add("animationClass-6252");
    document
      .querySelector("#id-105220")
      .removeEventListener("click", func_105220_15);

    setTimeout(() => {
      //loop login
      document.querySelector("#id-15").classList.remove("animationClass-15");
      document.querySelector("#id-111").classList.remove("animationClass-111");
      document.querySelector("#id-252").classList.remove("animationClass-252");
      document.querySelector("#id-253").classList.remove("animationClass-253");
      document.querySelector("#id-24").classList.remove("animationClass-24");
      document.querySelector("#id-23").classList.remove("animationClass-23");
      document.querySelector("#id-211").classList.remove("animationClass-211");
      document
        .querySelector(".ira-1-308722-0")
        .classList.remove("animationClass-115-115-0");
      document.querySelector("#id-115").classList.remove("animationClass-115");
      document.querySelector("#id-219").classList.remove("animationClass-219");
      document.querySelector("#id-220").classList.remove("animationClass-220");
      document.querySelector("#id-221").classList.remove("animationClass-221");
      document
        .querySelector(".car-1-10816-0")
        .classList.remove("animationClass-222-222-0");
      document.querySelector("#id-222").classList.remove("animationClass-222");
      document.querySelector("#id-215").classList.remove("animationClass-215");
      document.querySelector("#id-216").classList.remove("animationClass-216");
      document.querySelector("#id-217").classList.remove("animationClass-217");
      document
        .querySelector(".c-401k-1-563539-0")
        .classList.remove("animationClass-218-218-0");
      document.querySelector("#id-218").classList.remove("animationClass-218");
      document
        .querySelector("#id-4864")
        .classList.remove("animationClass-4864");
      document
        .querySelector(".investment-acco-1-591360-0")
        .classList.remove("animationClass-4850-4850-0");
      document
        .querySelector("#id-4850")
        .classList.remove("animationClass-4850");
      document
        .querySelector("#id-57104")
        .classList.remove("animationClass-57104");
      document
        .querySelector("#id-57105")
        .classList.remove("animationClass-57105");
      document
        .querySelector("#id-105217")
        .classList.remove("nullAnimation-105217");
      document
        .querySelector("#id-105218")
        .classList.remove("nullAnimation-105218");
      document
        .querySelector("#id-105219")
        .classList.remove("nullAnimation-105219");
      document
        .querySelector("#id-105235")
        .classList.remove("nullAnimation-105235");
      document
        .querySelector("#id-105236")
        .classList.remove("nullAnimation-105236");
      document
        .querySelector("#id-105225")
        .classList.remove("nullAnimation-105225");
      document
        .querySelector("#id-105226")
        .classList.remove("nullAnimation-105226");
      document
        .querySelector("#id-105227")
        .classList.remove("nullAnimation-105227");
      document
        .querySelector("#id-105228")
        .classList.remove("nullAnimation-105228");
      document
        .querySelector("#id-105229")
        .classList.remove("nullAnimation-105229");
      document
        .querySelector("#id-105220")
        .classList.remove("nullAnimation-105220");
      document
        .querySelector("#id-105221")
        .classList.remove("nullAnimation-105221");
      document
        .querySelector("#id-105222")
        .classList.remove("nullAnimation-105222");
      document
        .querySelector("#id-105223")
        .classList.remove("nullAnimation-105223");
      document
        .querySelector("#id-105224")
        .classList.remove("nullAnimation-105224");
      document
        .querySelector("#id-105230")
        .classList.remove("nullAnimation-105230");
      document
        .querySelector("#id-105231")
        .classList.remove("nullAnimation-105231");
      document
        .querySelector("#id-105233")
        .classList.remove("nullAnimation-105233");
      document
        .querySelector("#id-105232")
        .classList.remove("nullAnimation-105232");
      document
        .querySelector("#id-105234")
        .classList.remove("nullAnimation-105234");
      document.querySelector("#id-6290").classList.remove("nullAnimation-6290");
      document.querySelector("#id-6291").classList.remove("nullAnimation-6291");
      document.querySelector("#id-6292").classList.remove("nullAnimation-6292");
      document
        .querySelector("#id-10110")
        .classList.remove("nullAnimation-10110");
      document.querySelector("#id-3712").classList.remove("nullAnimation-3712");
      document.querySelector("#id-223").classList.remove("nullAnimation-223");
      document
        .querySelector("#id-94231")
        .classList.remove("nullAnimation-94231");
      document.querySelector("#id-3027").classList.remove("nullAnimation-3027");
      document
        .querySelector("#id-94169")
        .classList.remove("nullAnimation-94169");
      document.querySelector("#id-2511").classList.remove("nullAnimation-2511");
      document.querySelector("#id-258").classList.remove("nullAnimation-258");
      document.querySelector("#id-259").classList.remove("nullAnimation-259");
      document.querySelector("#id-2510").classList.remove("nullAnimation-2510");
      document
        .querySelector("#id-10111")
        .classList.remove("nullAnimation-10111");
      document.querySelector("#id-257").classList.remove("nullAnimation-257");
      document.querySelector("#id-254").classList.remove("nullAnimation-254");
      document.querySelector("#id-255").classList.remove("nullAnimation-255");
      document.querySelector("#id-256").classList.remove("nullAnimation-256");
      document
        .querySelector("#id-94230")
        .classList.remove("nullAnimation-94230");
      document.querySelector("#id-2516").classList.remove("nullAnimation-2516");
      document.querySelector("#id-2514").classList.remove("nullAnimation-2514");
      document.querySelector("#id-2512").classList.remove("nullAnimation-2512");
      document.querySelector("#id-2513").classList.remove("nullAnimation-2513");
      document
        .querySelector("#id-102")
        .classList.remove("animationClass-null102");
      document
        .querySelector("#id-1010")
        .classList.remove("animationClass-null1010");
      document
        .querySelector("#id-4561")
        .classList.remove("animationClass-null4561");
      document
        .querySelector("#id-1029")
        .classList.remove("animationClass-null1029");
      document
        .querySelector("#id-1030")
        .classList.remove("animationClass-null1030");
      document
        .querySelector("#id-1031")
        .classList.remove("animationClass-null1031");
      document
        .querySelector("#id-1032")
        .classList.remove("animationClass-null1032");
      document
        .querySelector("#id-1032 > div:first-child")
        .classList.remove("bgClass-1032");
      document
        .querySelector("#id-1023")
        .classList.remove("animationClass-null1023");
      document
        .querySelector("#id-1018")
        .classList.remove("animationClass-null1018");
      document
        .querySelector("#id-1014")
        .classList.remove("animationClass-null1014");
      document
        .querySelector("#id-1034")
        .classList.remove("animationClass-null1034");
      document
        .querySelector("#id-1034 > div:first-child")
        .classList.remove("bgClass-1034");
      document
        .querySelector("#id-1024")
        .classList.remove("animationClass-null1024");
      document
        .querySelector("#id-1019")
        .classList.remove("animationClass-null1019");
      document
        .querySelector("#id-1015")
        .classList.remove("animationClass-null1015");
      document
        .querySelector("#id-1036")
        .classList.remove("animationClass-null1036");
      document
        .querySelector("#id-1036 > div:first-child")
        .classList.remove("bgClass-1036");
      document
        .querySelector("#id-1022")
        .classList.remove("animationClass-null1022");
      document
        .querySelector("#id-1017")
        .classList.remove("animationClass-null1017");
      document
        .querySelector("#id-1012")
        .classList.remove("animationClass-null1012");
      document
        .querySelector("#id-1035")
        .classList.remove("animationClass-null1035");
      document
        .querySelector("#id-1035 > div:first-child")
        .classList.remove("bgClass-1035");
      document
        .querySelector("#id-1021")
        .classList.remove("animationClass-null1021");
      document
        .querySelector("#id-1016")
        .classList.remove("animationClass-null1016");
      document
        .querySelector("#id-1013")
        .classList.remove("animationClass-null1013");
      document
        .querySelector("#id-1033")
        .classList.remove("animationClass-null1033");
      document
        .querySelector("#id-1033 > div:first-child")
        .classList.remove("bgClass-1033");
      document
        .querySelector("#id-3745")
        .classList.remove("animationClass-null3745");
      document
        .querySelector("#id-3746")
        .classList.remove("animationClass-null3746");
      document
        .querySelector("#id-3759")
        .classList.remove("animationClass-null3759");
      document
        .querySelector("#id-3759 > div:first-child")
        .classList.remove("bgClass-3759");
      document
        .querySelector("#id-3751")
        .classList.remove("animationClass-null3751");
      document
        .querySelector("#id-3752")
        .classList.remove("animationClass-null3752");
      document
        .querySelector("#id-3753")
        .classList.remove("animationClass-null3753");
      document
        .querySelector("#id-3754")
        .classList.remove("animationClass-null3754");
      document
        .querySelector("#id-3747")
        .classList.remove("animationClass-null3747");
      document
        .querySelector("#id-3748")
        .classList.remove("animationClass-null3748");
      document
        .querySelector("#id-3749")
        .classList.remove("animationClass-null3749");
      document
        .querySelector("#id-3750")
        .classList.remove("animationClass-null3750");
      document
        .querySelector("#id-3750 > div:first-child")
        .classList.remove("bgClass-3750");
      document
        .querySelector("#id-3755")
        .classList.remove("animationClass-null3755");
      document
        .querySelector("#id-3757")
        .classList.remove("animationClass-null3757");
      document
        .querySelector("#id-3756")
        .classList.remove("animationClass-null3756");
      document
        .querySelector("#id-3756 > div:first-child")
        .classList.remove("bgClass-3756");
      document
        .querySelector("#id-3758")
        .classList.remove("animationClass-null3758");
      document
        .querySelector("#id-3758 > div:first-child")
        .classList.remove("bgClass-3758");
      document.querySelector("#id-6252").classList.remove("nullAnimation-6252");
      document.querySelector("#id-6253").classList.remove("nullAnimation-6253");
      document.querySelector("#id-6254").classList.remove("nullAnimation-6254");
      document.querySelector("#id-6255").classList.remove("nullAnimation-6255");
      document.querySelector("#id-6258").classList.remove("nullAnimation-6258");
      document.querySelector("#id-6256").classList.remove("nullAnimation-6256");
      document.querySelector("#id-6257").classList.remove("nullAnimation-6257");
      document
        .querySelector("#id-10110")
        .classList.remove("animationClass-10110");
      document.querySelector("#id-15").classList.remove("animationClass-4854");
      document.querySelector("#id-111").classList.remove("nullAnimation-111");
      document.querySelector("#id-252").classList.remove("nullAnimation-252");
      document.querySelector("#id-253").classList.remove("nullAnimation-253");
      document.querySelector("#id-24").classList.remove("nullAnimation-24");
      document.querySelector("#id-219").classList.remove("nullAnimation-219");
      document.querySelector("#id-215").classList.remove("nullAnimation-215");
      document.querySelector("#id-4864").classList.remove("nullAnimation-4864");
      document
        .querySelector("#id-105217")
        .classList.remove("animationClass-null105217");
      document
        .querySelector("#id-105218")
        .classList.remove("animationClass-null105218");
      document
        .querySelector("#id-105219")
        .classList.remove("animationClass-null105219");
      document
        .querySelector("#id-105235")
        .classList.remove("animationClass-null105235");
      document
        .querySelector("#id-105236")
        .classList.remove("animationClass-null105236");
      document
        .querySelector("#id-105236 > div:first-child")
        .classList.remove("bgClass-105236");
      document
        .querySelector("#id-105225")
        .classList.remove("animationClass-null105225");
      document
        .querySelector("#id-105226")
        .classList.remove("animationClass-null105226");
      document
        .querySelector("#id-105227")
        .classList.remove("animationClass-null105227");
      document
        .querySelector("#id-105228")
        .classList.remove("animationClass-null105228");
      document
        .querySelector("#id-105229")
        .classList.remove("animationClass-null105229");
      document
        .querySelector("#id-105220")
        .classList.remove("animationClass-null105220");
      document
        .querySelector("#id-105221")
        .classList.remove("animationClass-null105221");
      document
        .querySelector("#id-105222")
        .classList.remove("animationClass-null105222");
      document
        .querySelector("#id-105223")
        .classList.remove("animationClass-null105223");
      document
        .querySelector("#id-105224")
        .classList.remove("animationClass-null105224");
      document
        .querySelector("#id-105224 > div:first-child")
        .classList.remove("bgClass-105224");
      document
        .querySelector("#id-105230")
        .classList.remove("animationClass-null105230");
      document
        .querySelector("#id-105231")
        .classList.remove("animationClass-null105231");
      document
        .querySelector("#id-105233")
        .classList.remove("animationClass-null105233");
      document
        .querySelector("#id-105232")
        .classList.remove("animationClass-null105232");
      document
        .querySelector("#id-105232 > div:first-child")
        .classList.remove("bgClass-105232");
      document
        .querySelector("#id-105234")
        .classList.remove("animationClass-null105234");
      document
        .querySelector("#id-105234 > div:first-child")
        .classList.remove("bgClass-105234");
      document
        .querySelector("#id-6290")
        .classList.remove("animationClass-null6290");
      document
        .querySelector("#id-6291")
        .classList.remove("animationClass-null6291");
      document
        .querySelector("#id-6292")
        .classList.remove("animationClass-null6292");
      document
        .querySelector("#id-6292 > div:first-child")
        .classList.remove("bgClass-6292");
      document.querySelector("#id-102").classList.remove("animationClass-102");
      document
        .querySelector("#id-6252")
        .classList.remove("animationClass-null6252");
      document
        .querySelector("#id-6253")
        .classList.remove("animationClass-null6253");
      document
        .querySelector("#id-6254")
        .classList.remove("animationClass-null6254");
      document
        .querySelector("#id-6255")
        .classList.remove("animationClass-null6255");
      document
        .querySelector("#id-6258")
        .classList.remove("animationClass-null6258");
      document
        .querySelector("#id-6256")
        .classList.remove("animationClass-null6256");
      document
        .querySelector("#id-6257")
        .classList.remove("animationClass-null6257");
      document
        .querySelector("#id-10110")
        .classList.remove("nullAnimation-10110");
      document.querySelector("#id-15").classList.remove("animationClass-6251");
      document
        .querySelector("#id-111")
        .classList.remove("animationClass-null111");
      document
        .querySelector("#id-252")
        .classList.remove("animationClass-null252");
      document
        .querySelector("#id-253")
        .classList.remove("animationClass-null253");
      document
        .querySelector("#id-24")
        .classList.remove("animationClass-null24");
      document
        .querySelector("#id-219")
        .classList.remove("animationClass-null219");
      document
        .querySelector("#id-215")
        .classList.remove("animationClass-null215");
      document
        .querySelector("#id-4864")
        .classList.remove("animationClass-null4864");
      document
        .querySelector("#id-105217")
        .classList.remove("animationClass-105217");
      document
        .querySelector("#id-6290")
        .classList.remove("animationClass-6290");
      document
        .querySelector("#id-10110")
        .classList.remove("animationClass-null10110");
      document
        .querySelector("#id-3712")
        .classList.remove("animationClass-null3712");
      document
        .querySelector("#id-223")
        .classList.remove("animationClass-null223");
      document
        .querySelector("#id-94231")
        .classList.remove("animationClass-null94231");
      document
        .querySelector("#id-3027")
        .classList.remove("animationClass-null3027");
      document
        .querySelector("#id-3027 > div:first-child")
        .classList.remove("bgClass-3027");
      document
        .querySelector("#id-94169")
        .classList.remove("animationClass-null94169");
      document
        .querySelector("#id-2511")
        .classList.remove("animationClass-null2511");
      document
        .querySelector("#id-258")
        .classList.remove("animationClass-null258");
      document
        .querySelector("#id-259")
        .classList.remove("animationClass-null259");
      document
        .querySelector("#id-2510")
        .classList.remove("animationClass-null2510");
      document
        .querySelector("#id-10111")
        .classList.remove("animationClass-null10111");
      document
        .querySelector("#id-257")
        .classList.remove("animationClass-null257");
      document
        .querySelector("#id-254")
        .classList.remove("animationClass-null254");
      document
        .querySelector("#id-255")
        .classList.remove("animationClass-null255");
      document
        .querySelector("#id-256")
        .classList.remove("animationClass-null256");
      document
        .querySelector("#id-256 > div:first-child")
        .classList.remove("bgClass-256");
      document
        .querySelector("#id-94230")
        .classList.remove("animationClass-null94230");
      document
        .querySelector("#id-2516")
        .classList.remove("animationClass-null2516");
      document
        .querySelector("#id-2514")
        .classList.remove("animationClass-null2514");
      document
        .querySelector("#id-2512")
        .classList.remove("animationClass-null2512");
      document
        .querySelector("#id-2512 > div:first-child")
        .classList.remove("bgClass-2512");
      document
        .querySelector("#id-2513")
        .classList.remove("animationClass-null2513");
      document
        .querySelector("#id-2513 > div:first-child")
        .classList.remove("bgClass-2513");
      document.querySelector("#id-102").classList.remove("nullAnimation-102");
      document
        .querySelector("#id-6252")
        .classList.remove("animationClass-6252");
      runAnimations();
    }, 1);
  }
}
export default runAnimations;
// links object
export const allLinks = {};

// function object
export const allFunctions = {};
